<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>classparser</artifactId>
        <groupId>com.classparser</groupId>
        <version>1.0.0</version>
    </parent>

    <artifactId>classparser-bytecode</artifactId>
    <version>1.0.0</version>

    <description>
        Module store classes for bytecode decompile parsing mechanism
    </description>

    <!-- 
    The jitpack repository for building the fernflower
    from github.com by repo fesh0r/fernflower
     -->
    <repositories>
        <repository>
            <id>jitpack</id>
            <name>jitpack-repository</name>
            <url>https://jitpack.io/</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- FernFlower Decompiler -->
        <dependency>
            <groupId>com.github.fesh0r</groupId>
            <artifactId>fernflower</artifactId>
            <version>5b1461a3ba</version>
        </dependency>

        <!-- Modules-->
        <dependency>
            <groupId>com.classparser</groupId>
            <artifactId>classparser-core</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</project>